In [1]:
from py_sudoku import Sudoku
from random import seed
from numpy import equal
seed(1)
puzzle = Sudoku()
# Random create the whole Sudoku.
realans = puzzle.board
print(realans)

[[6 3 9 2 5 8 4 1 7]
 [4 5 7 3 1 9 8 6 2]
 [2 8 1 7 4 6 9 5 3]
 [5 9 3 6 2 4 1 7 8]
 [8 2 4 5 7 1 3 9 6]
 [1 7 6 8 9 3 2 4 5]
 [7 4 2 9 8 5 6 3 1]
 [3 1 5 4 6 2 7 8 9]
 [9 6 8 1 3 7 5 2 4]]


In [2]:
# set the difficulty 0~1 recommend below 0.7.
puzzle.difficulty(0.6)
# get the sudoku puzzle by digging holes.
puzzle.generator()
problem = puzzle.board
print(problem)

[[6 0 9 2 5 8 0 0 0]
 [4 5 7 0 0 0 8 0 2]
 [2 0 0 0 4 0 0 5 0]
 [5 9 3 6 0 0 1 0 8]
 [8 0 0 5 7 0 3 9 0]
 [1 0 6 8 9 0 2 4 5]
 [0 4 2 9 0 5 0 3 1]
 [0 1 5 4 0 2 0 8 0]
 [9 0 8 0 3 7 5 0 4]]


In [4]:
# solve the sudoku puzzle and test it.
puzzle.solver()
ans = puzzle.board
print(ans)
print(equal(ans, realans).all())

[[6 3 9 2 5 8 4 1 7]
 [4 5 7 3 1 9 8 6 2]
 [2 8 1 7 4 6 9 5 3]
 [5 9 3 6 2 4 1 7 8]
 [8 2 4 5 7 1 3 9 6]
 [1 7 6 8 9 3 2 4 5]
 [7 4 2 9 8 5 6 3 1]
 [3 1 5 4 6 2 7 8 9]
 [9 6 8 1 3 7 5 2 4]]
True


In [5]:
puzzlemn = Sudoku(3, 4)
ans = puzzlemn.board
print(ans)
puzzlemn.generator()
mnarray = puzzlemn.board
print()
print(mnarray)


[[ 4 12  5 10  6  8  9  7  2  3  1 11]
 [ 7 11  2  1 10 12  3  5  4  8  6  9]
 [ 8  9  6  3  4  2  1 11 10  7  5 12]
 [ 9  2  3  8  1  7 11 10  5  4 12  6]
 [ 6  7  4 11 12  3  5  8  9  1 10  2]
 [ 5  1 10 12  9  6  2  4  8 11  3  7]
 [12  3  1  7  2  4  6  9 11 10  8  5]
 [ 2 10  8  6  5 11  7  3  1 12  9  4]
 [11  5  9  4  8  1 10 12  6  2  7  3]
 [ 1  8  7  5  3  9  4  2 12  6 11 10]
 [10  6 11  2  7  5 12  1  3  9  4  8]
 [ 3  4 12  9 11 10  8  6  7  5  2  1]]

[[ 0 12  0 10  6  8  0  7  2  3  0  0]
 [ 7 11  0  0  0  0  3  5  4  8  0  9]
 [ 8  0  6  0  0  2  1 11  0  7  0  0]
 [ 9  2  0  0  0  0  0  0  0  0  0  6]
 [ 0  7  4 11 12  3  0  8  9  1 10  2]
 [ 5  0 10  0  0  6  0  4  0 11  3  7]
 [ 0  3  1  7  0  4  0  0  0  0  0  0]
 [ 0 10  0  0  5  0  7  3  1  0  0  4]
 [11  0  0  0  8  1 10  0  6  0  0  3]
 [ 1  8  0  5  0  0  0  0  0  0 11 10]
 [ 0  6  0  0  0  0 12  0  3  0  4  8]
 [ 3  4  0  0 11 10  0  0  7  0  0  1]]
